// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechChallengeApi.Data;

#nullable disable

namespace TechChallengeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130235522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TechChallengeApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Capas colecionáveis de álbuns, incluindo fotos inéditas. Encarte colecionável de 24 páginas encadernada em livro com três letras manuscritas exclusivas para este vinil e fotos inéditas\r\n",
                            ImageUrl = "/img/ttpd.png",
                            Name = "Vinil: The Tortured Poets Dept.",
                            Price = 589.90m
                        },
                        new
                        {
                            Id = 2,
                            Description = "O oitavo álbum de Taylor Swift, folklore foi lançado de forma surpreendente em julho de 2020. Possui 17 faixas, incluindo o single  “Cardigan”.",
                            ImageUrl = "/img/folklore.png",
                            Name = "Vinil: Folklore (LP Vermelho - Target)",
                            Price = 600.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Intitulado “midnights”, o trabalho é descrito por Taylor “como uma coleção de 13 faixas escritas durante a madrugada, uma jornada de terror e doces sonhos”. O lançamento ocorre em 21 de outubro de 2022.",
                            ImageUrl = "/img/midnights.png",
                            Name = "Vinil: Midnights (LP Azul)",
                            Price = 489.90m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vinil 5 Seconds Of Summer – Everyone’s a Star (Autografado).",
                            ImageUrl = "/img/EAS.png",
                            Name = "Vinil: Everyone’s a Star (Autografado)",
                            Price = 389.90m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tricô creme texturizado com estrelas prateadas bordadas nos cotovelos.",
                            ImageUrl = "/img/breach.png",
                            Name = "Vinil: Breach (Target Edition)",
                            Price = 420.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Man’s Best Friend é o mais recente álbum da multifacetada popstar global Sabrina Carpenter. Após seu projeto vencedor do GRAMMY Short n’ Sweet e vários singles multi-platina adicionados ao seu currículo, o mais recente de Carpenter apresenta seu novo single “Manchild”, disponível agora. disco opaco azul claro imagem em formato gatefold pôster padrão encarte (com a lista de faixas) capa de vinil (com os créditos).",
                            ImageUrl = "/img/MBF.png",
                            Name = "Vinil: Man's Best Friend D2C Bonus Track LP",
                            Price = 549.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
